server:
  port:7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
  username: spring
  password: 1234
  jpa:
    hibernate:
      ddl-auto: update

myapp:
  url: http://localhost:5000/api/product/add-product
  secret-key: my-secret-value
