server:
  port:7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_details
  username: spring
  password: 1234

jpa: hibernate.ddl-auto=update

secret: my-secret-value
url: http://localhost:5000/api/product/add-product