server.port: 5000

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product_details
    username: spring
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update


